[package]
name = "dcr"
version = "0.1.0"
authors = ["David Buret <rmotfage@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "1.0.0"
actix-files = "0.1.1"
bytes = "0.4.12"
futures = "0.1.27"
log = "0.4.0"
env_logger = "0.6.1"
actix-rt = "0.2.2"